"""initial schema: analyses, qa_sessions, llm_cache

Revision ID: 2ad6ea492fb4
Revises: 
Create Date: 2026-07-04 14:13:52.688513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad6ea492fb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('idea', sa.Text(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('overall_readiness_score', sa.Float(), nullable=True),
    sa.Column('demand_score', sa.Float(), nullable=True),
    sa.Column('regulatory_score', sa.Float(), nullable=True),
    sa.Column('analysis_mode', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('qa_completed', sa.Boolean(), nullable=False),
    sa.Column('qa_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_table('llm_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_cache_prompt_hash'), 'llm_cache', ['prompt_hash'], unique=True)
    op.create_table('qa_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('current_question', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_sessions_analysis_id'), 'qa_sessions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_qa_sessions_id'), 'qa_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_sessions_id'), table_name='qa_sessions')
    op.drop_index(op.f('ix_qa_sessions_analysis_id'), table_name='qa_sessions')
    op.drop_table('qa_sessions')
    op.drop_index(op.f('ix_llm_cache_prompt_hash'), table_name='llm_cache')
    op.drop_table('llm_cache')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
